name: Makefile Linter

on:
  workflow_dispatch: {}
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - "**Makefile*" # Only trigger when Makefile files are modified

jobs:
  shellcheck:
    name: Run Checkmake on Updated Makefiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Checkmake
        run: sudo apt-get install -y checkmake

      - name: Find Modified Shell Scripts
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: "**Makefile"

      - name: Run Checkmake
        if: steps.changed-files.outputs.any_changed == 'true'
        run:
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "🔍 Running checkmake on $file..."
              checkmake "$file" || { echo "❌ checkmake found issues. Please fix them."; exit 1; }
          done
