name: ShellCheck Linter

on:
  workflow_dispatch: {}
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - "**.sh" # Only trigger when .sh files are modified

jobs:
  shellcheck:
    name: Run ShellCheck on Updated Bash Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install ShellCheck and shfmt
        run: sudo apt-get install -y shellcheck shfmt

      - name: Find Modified Shell Scripts
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: "**.sh"

      - name: Run ShellCheck
        if: steps.changed-files.outputs.any_changed == 'true'
        run:
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "🔍 Running ShellCheck on $file..."
              shellcheck "$file"
          done

      - name: Run shfmt and Check for Formatting Issues
        if: steps.changed-files.outputs.any_changed == 'true'
        run:
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "🔍 Running shfmt on $file..."
              shfmt -d "$file" || { echo "❌ shfmt detected formatting issues in $file. Please run 'shfmt -w $file' locally."; exit 1; }
          done
